package it.docSys.services.impl;


import it.docSys.DTO.GetDocumentDTO;
import it.docSys.DTO.PutDocumentDTO;
import it.docSys.model.Document;
import it.docSys.repository.DocumentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

//TODO Finish Conversion of Entities to DTO and make CRUD Work!      Seems to be Done

@Service
//@Transactional(readOnly = true)
public class DocumentServiceImpl {

    @Autowired
    private DocumentRepository documentRepository;


    public DocumentServiceImpl(DocumentRepository documentRepository) {
        this.documentRepository = documentRepository;
    }

//TODO There is no ID Provided it is @Autogenerated in @Entity, but it may cause some problems!
    @Transactional
    public void create(PutDocumentDTO putDocumentDTO) {
    Document document = new Document();
    document.setAddressee(putDocumentDTO.getAddressee());
    document.setApprovingDate(putDocumentDTO.getApprovingDate());
    document.setAttachments(putDocumentDTO.getAttachments());
    document.setAuthor(putDocumentDTO.getAuthor());
    document.setDescription(putDocumentDTO.getDescription());
    document.setName(putDocumentDTO.getName());
    document.setRejectionDate(putDocumentDTO.getRejectionDate());
    document.setRejectionReason(putDocumentDTO.getRejectionReason());
    document.setSubmissionDate(putDocumentDTO.getSubmissionDate());
    document.setType(putDocumentDTO.getType());
    documentRepository.save(document);
    }

//    @Override
//    public Document get(long id) {
//        return documentRepository.getOne(id);
//    }

        @Transactional
        public GetDocumentDTO get(Long id) {
            Document document = documentRepository.findById(id).orElse(null);
            if (document != null) {
                return new GetDocumentDTO(document.getId(), document.getAuthor(), document.getType(),
                        document.getName(), document.getDescription(), document.getSubmissionDate(),
                        document.getApprovingDate(), document.getRejectionDate(), document.getAddressee(),
                        document.getRejectionReason(), document.getAttachments());
            }
            return null;
    }

    public List<GetDocumentDTO> listAll() {
        return documentRepository.findAll().stream().map(document ->
                new GetDocumentDTO(document.getId(), document.getAuthor(), document.getType(),
                        document.getName(), document.getDescription(), document.getSubmissionDate(),
                        document.getApprovingDate(), document.getRejectionDate(), document.getAddressee(),
                        document.getRejectionReason(), document.getAttachments())).collect(Collectors.toList());
    }

//    @Transactional
//    @Override
//    public void update(long id, Document document) {
//        Document doc =  documentRepository.getOne(id);
//        documentRepository.save(doc);
//

    //TODO or may instantiate it as document1, cuz it worked

    @Transactional
    public void update(long id, PutDocumentDTO putDocumentDTO) {
        Document document = documentRepository.findById(id).orElse(null);
        if (document != null){
//            document.setId(putDocumentDTO.getId());
            document.setAddressee(putDocumentDTO.getAddressee());
            document.setApprovingDate(putDocumentDTO.getApprovingDate());
            document.setAttachments(putDocumentDTO.getAttachments());
            document.setAuthor(putDocumentDTO.getAuthor());
            document.setDescription(putDocumentDTO.getDescription());
            document.setName(putDocumentDTO.getName());
            document.setRejectionDate(putDocumentDTO.getRejectionDate());
            document.setRejectionReason(putDocumentDTO.getRejectionReason());
            document.setSubmissionDate(putDocumentDTO.getSubmissionDate());
            document.setType(putDocumentDTO.getType());
        }
    }

    @Transactional
     public void delete(long id) {
    documentRepository.deleteById(id);
    }

}

